-- MySQL Script generated by MySQL Workbench
-- vie 15 jul 2022 10:06:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema okeio_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema okeio_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `okeio_db` DEFAULT CHARACTER SET utf8 ;
USE `okeio_db` ;

-- -----------------------------------------------------
-- Table `okeio_db`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okeio_db`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `okeio_db`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okeio_db`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okeio_db`.`Productos` ;

CREATE TABLE IF NOT EXISTS `okeio_db`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `sustancia_activa` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  `precio` FLOAT NOT NULL,
  `existencia` INT NOT NULL DEFAULT 0,
  `porcion` VARCHAR(10) NOT NULL,
  `estatus` CHAR(1) NOT NULL,
  `receta_obligatoria` CHAR(1) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `ruta_imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okeio_db`.`Tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okeio_db`.`Tickets` ;

CREATE TABLE IF NOT EXISTS `okeio_db`.`Tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `subtotal` FLOAT NOT NULL DEFAULT 0,
  `iva` FLOAT NOT NULL,
  `total` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `okeio_db`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okeio_db`.`producto_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `okeio_db`.`producto_ticket` ;

CREATE TABLE IF NOT EXISTS `okeio_db`.`producto_ticket` (
  `id` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_ticket` INT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_ticket_idx` (`id_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `okeio_db`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `okeio_db`.`Tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
